include:
  - remote: 'https://gitlab.com/Kozea/ci-master/raw/master/.variables-images.yml'
  - remote: 'https://gitlab.com/Kozea/ci-master/raw/master/.ci-install.yml'
  - remote: 'https://gitlab.com/Kozea/ci-master/raw/master/.ci-build.yml'
  - remote: 'https://gitlab.com/Kozea/ci-master/raw/master/.ci-lint.yml'
  - remote: 'https://gitlab.com/Kozea/ci-master/raw/master/.ci-test.yml'
  - remote: 'https://gitlab.com/Kozea/ci-master/raw/master/.ci-deploy-test.yml'

.image_test_jobs:
  image: kozea/python-node-yarn-postgresql:latest

stages:
  - install
  - build
  - test
  - deploy_test

.artifacts_install: &artifacts_install
  artifacts:
    paths:
      - node_modules/
      - .venv/

.artifacts_build: &artifacts_build
  artifacts:
    paths:
      - lib/frontend/static/
      - node_modules/
      - .venv/

install:
  <<: *artifacts_install

build:
  <<: *artifacts_build
