variables:
  PYTHON_VERSION: python
  STAGING: y

stages:
  - install
  - build
  - test
  - deploy_test

.artifacts: &artifacts_install
  artifacts:
    paths:
      - node_modules/
      - .venv/

.artifacts: &artifacts_build
  artifacts:
    paths:
      - lib/frontend/static/
      - node_modules/
      - .venv/

image: paradoxxxzero/python-node-yarn-postgresql:latest

install_latest:
  stage: install
  script:
    - pip install pipenv
    - make install
  <<: *artifacts_install

build_latest:
  stage: build
  script: make build
  <<: *artifacts_build
  dependencies:
    - install_latest

lint_latest:
  stage: test
  script:
    - pip install pipenv
    - make lint
  dependencies:
    - build_latest

test_latest:
  stage: test
  script:
    - pip install pipenv
    - make check
  dependencies:
    - build_latest


.image: &image_deploy_jobs
  image: debian:latest

deploy_test:
  <<: *image_deploy_jobs
  stage: deploy_test
  before_script:
    - "apt-get update && apt-get install -y curl"
  script:
    - "branch_name=`echo $CI_COMMIT_REF_NAME | tr -cd '[[:alnum:]]'`"
    - "output_file=/tmp/$CI_PROJECT_NAME-$branch_name-36.log"
    - "url_test_current=https://test-$CI_PROJECT_NAME-$branch_name-36.kozea.fr"
    - "url_test_api_current=https://test-$CI_PROJECT_NAME-$branch_name-36.kozea.fr/api/date.json"
    - "stdbuf -o 0 curl --http1.1 -m 3600 -N -s -H 'Content-Type: application/json' -X POST -d '{\"job_id\":\"'\"$CI_JOB_ID\"'\", \"token\":\"\'\"$TOKEN\"\'\", \"url\":\"\'\"$CI_REPOSITORY_URL\"\'\", \"build_stage\":\"\'\"$CI_JOB_STAGE\"\'\", \"project_name\":\"\'\"$CI_PROJECT_NAME\"\'\", \"branch\":\"\'\"$CI_COMMIT_REF_NAME\"\'\", \"password\":\"\'\"$PASSWD\"\'\", \"commit_sha\":\"\'\"$CI_COMMIT_SHA\"\'\", \"url_test\":\"\'\"$url_test\"\'\"}' $JUNKRAT | tee $output_file"
    - "[ $(tail -n1 $output_file) == 'Success' ] || exit 1"
    - "get=`curl -s -o -I -w \"%{http_code}\" $url_test_current`"
    - "exit $([[ $get = 302 || $get = 200 ]])"
    - "get_api=`curl -s -o -I -w \"%{http_code}\" $url_test_api_current`"
    - "exit $([[ $get_api = 302 || $get_api = 200 ]])"
  dependencies: []
