variables:
  PYTHON_VERSION: python
  STAGING: y

stages:
  - install
  - build
  - test
  - deploy_test

.artifacts: &artifacts_install
  artifacts:
    paths:
      - node_modules/
      - .env/

.artifacts: &artifacts_build
  artifacts:
    paths:
      - lib/frontend/static/
      - node_modules/
      - .env/


image: paradoxxxzero/python-node-yarn-postgresql:3.5-9.8-10.3

install3.5:
  stage: install
  script:
    - make install
  <<: *artifacts_install

build3.5:
  stage: build
  script: make build
  <<: *artifacts_build
  dependencies:
    - install3.5

lint3.5:
  stage: test
  script: make lint
  dependencies:
    - build3.5

test3.5:
  stage: test
  script: make check
  dependencies:
    - build3.5


.image: &image_latest
  image: paradoxxxzero/python-node-yarn-postgresql:latest

install_latest:
  <<: *image_latest
  stage: install
  script:
    - make install
  <<: *artifacts_install

build_latest:
  <<: *image_latest
  stage: build
  script: make build
  <<: *artifacts_build
  dependencies:
    - install_latest

lint_latest:
  <<: *image_latest
  stage: test
  script: make lint
  dependencies:
    - build_latest

test_latest:
  <<: *image_latest
  stage: test
  script: make check
  dependencies:
    - build_latest


.image: &image_deploy_jobs
  image: debian:latest

deploy_test:
  <<: *image_deploy_jobs
  stage: deploy_test
  before_script:
    - "apt-get update && apt-get install -y jq curl"
  script:
    - "branch_name=`echo $CI_COMMIT_REF_NAME | tr -cd '[[:alnum:]]'`"
    - "url_test=https://test-$CI_PROJECT_NAME-$branch_name.kozea.fr"
    - "url_test_api=https://test-$CI_PROJECT_NAME-$branch_name.kozea.fr/api"
    - "res_curl=`curl --http1.1 -m 3600 -H 'Content-Type: application/json' -X POST -d '{\"job_id\":\"'\"$CI_JOB_ID\"'\", \"token\":\"\'\"$TOKEN\"\'\", \"url\":\"\'\"$CI_REPOSITORY_URL\"\'\", \"build_stage\":\"\'\"$CI_JOB_STAGE\"\'\", \"project_name\":\"\'\"$CI_PROJECT_NAME\"\'\", \"branch\":\"\'\"$CI_COMMIT_REF_NAME\"\'\", \"password\":\"\'\"$PASSWD\"\'\", \"commit_sha\":\"\'\"$CI_COMMIT_SHA\"\'\", \"url_test\":\"\'\"$url_test\"\'\"}' $JUNKRAT | jq -r \'.success\'`"
    - "if [[ $res_curl = 1 ]]; then exit $res_curl;fi"
    - "get=`curl -s -o -I -w \"%{http_code}\" $url_test`"
    - "get_api=`curl -s -o -I -w \"%{http_code}\" $url_test_api`"
    - "([[ $get = 302 || $get = 200 ]] && [[ $res_curl = 0 ]]) && exit_val=0 || exit_val=1 && exit $exit_val"
    - "([[ $get_api = 302 || $get_api = 200 ]] && [[ $res_curl = 0 ]]) && exit_val=0 || exit_val=1 && exit $exit_val"
  dependencies: []
